ARG BASE_IMAGE=ubuntu:22.04

FROM ${BASE_IMAGE}

ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH:-}"
ENV TF_CPP_MIN_LOG_LEVEL=2

RUN pip install \
	numpy scikit-learn tensorflow==2.16.2

