ARG BASE_IMAGE=ubuntu:22.04

FROM ${BASE_IMAGE}

# Optional: Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

# Install Python manually
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.10 python3-pip python3-dev python3-venv wget curl python-is-python3

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
