FROM ubuntu:22.04

ARG RES_DIR="resources"

COPY ${RES_DIR}/requirements.txt ./
COPY ${RES_DIR}/apt.packages ./

RUN apt-get update && apt-get install -y --no-install-recommends \
    $(cat apt.packages) && \
    pip3 install \
	openai torch transformers huggingface_hub && \
    pip3 install --no-cache-dir -r requirements.txt

WORKDIR /app
