FROM tensorflow/tensorflow:2.15.0-gpu

ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH:-}"
ENV TF_CPP_MIN_LOG_LEVEL=2

COPY requirements.txt ./

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.10 python3-pip python3-dev python3-venv wget curl python-is-python3 && \
    pip3 install \
	numpy scikit-learn tensorflow==2.16.2 && \
    pip3 install --no-cache-dir -r requirements.txt

WORKDIR /app
