FROM tensorflow/tensorflow:2.15.0-gpu

ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH:-}"
ENV TF_CPP_MIN_LOG_LEVEL=2

ARG RES_DIR="resources"

COPY ${RES_DIR}/requirements.txt ./
COPY ${RES_DIR}/apt.packages ./

RUN apt-get update && apt-get install -y --no-install-recommends \
    $(cat apt.packages) && \
    pip3 install \
	xgboost numpy scikit-learn tensorflow==2.16.2 && \
    pip3 install --no-cache-dir -r requirements.txt

WORKDIR /app
