FROM ubuntu:22.04

COPY requirements.txt ./

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.10 python3-pip python3-dev python3-venv wget curl python-is-python3 && \
    pip3 install \
	openai torch transformers huggingface_hub && \
    pip3 install --no-cache-dir -r requirements.txt

WORKDIR /app
